#! /usr/bin/env python



wanted_flags = ['sse','sse2','sse3','ssse3','sse4_1','sse4_2', 'aes', 
                'pclmulqdq', 'avx', 'rdrnd', 'fsgsbase', 'f16c']

def get_native_cpu_flags():
    "Figure out CPU flags based on /proc/cpuinfo"
    f = open("/proc/cpuinfo");
    for line in f:
        v = line.split()
        if v[0] == "flags":
            return [x.upper() for x in v[2:] if x in wanted_flags]

def options(opt):
    opt.add_option('--dpdk-apps', action='store_true', 
                   default=False, help='Build DPDK apps')
    opt.add_option('--dpdk-examples', action='store_true', 
                   default=False, help='Build DPDK examples')
    pass

def configure(conf):
    pass

def distclean(bld):
    dpdk_target_prefix = "x86_64-"
    del_cmd = "rm -rf " + bld.path.abspath() + "/" + dpdk_target_prefix + "*"
    os.system(del_cmd)


import os
def build(bld):
    if bld.cmd == 'clean':
        dpdk_target_prefix = "x86_64-"
        del_cmd = "rm -rf " + bld.path.abspath() + "/" + dpdk_target_prefix + "*"
        os.system(del_cmd)
        return
    os.system("pwd")
    str =  "cd " + bld.path.abspath() + "; make install T=x86_64-ivshmem-linuxapp-gcc"
    os.system(str)
